# Generated by Django 6.1 on 2026-10-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/logo.png', upload_to='courses'),
        ),
    ]
